// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagementSystem.Models;

#nullable disable

namespace SchoolManagementSystem.Migrations
{
    [DbContext(typeof(LmsDbContext))]
    [Migration("20260129121524_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolManagementSystem.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Admin_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("AdminEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Admin_Email");

                    b.Property<string>("AdminName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Admin_Name");

                    b.Property<string>("AdminPass")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Admin_Pass");

                    b.HasKey("AdminId");

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Attendance", b =>
                {
                    b.Property<DateTime>("ADate")
                        .HasColumnType("datetime")
                        .HasColumnName("A_Date");

                    b.Property<string>("ARemarks")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Not Provided")
                        .HasColumnName("A_Remarks");

                    b.Property<string>("AStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("A_Status");

                    b.Property<int>("AStdId")
                        .HasColumnType("int")
                        .HasColumnName("A_StdID");

                    b.HasIndex(new[] { "AStdId" }, "IX_Attendance_StdID");

                    b.ToTable("Attendance", (string)null);
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Classroom", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Class_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassDescription")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("NoDescription")
                        .HasColumnName("Class_Description");

                    b.HasKey("ClassId");

                    b.ToTable("Classroom", (string)null);
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Employee", b =>
                {
                    b.Property<int>("EId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("E_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EId"));

                    b.Property<DateOnly>("EDob")
                        .HasColumnType("date")
                        .HasColumnName("E_DOB");

                    b.Property<DateOnly>("EDoj")
                        .HasColumnType("date")
                        .HasColumnName("E_DOJ");

                    b.Property<string>("EEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("E_Email");

                    b.Property<string>("EFname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("E_Fname");

                    b.Property<string>("EGender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("E_Gender");

                    b.Property<string>("ELname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("E_Lname");

                    b.Property<string>("EMobileNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("E_MobileNo");

                    b.Property<string>("EPass")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("E_Pass");

                    b.Property<int>("ERoleId")
                        .HasColumnType("int")
                        .HasColumnName("E_RoleID");

                    b.Property<decimal>("ESalary")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("E_Salary");

                    b.Property<string>("EStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("E_Status");

                    b.Property<string>("ETelNo")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Not Provided")
                        .HasColumnName("E_TelNo");

                    b.HasKey("EId");

                    b.HasIndex("ERoleId");

                    b.HasIndex(new[] { "EMobileNo" }, "UQ_Employee_Mobile")
                        .IsUnique();

                    b.ToTable("Employee", null, t =>
                        {
                            t.HasTrigger("trg_Employee_Audit_Update");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.EventOnEmployee", b =>
                {
                    b.Property<DateTime?>("ChangeTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("change_time")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("EDob")
                        .HasColumnType("date")
                        .HasColumnName("E_DOB");

                    b.Property<DateOnly?>("EDoj")
                        .HasColumnType("date")
                        .HasColumnName("E_DOJ");

                    b.Property<string>("EEmail")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("E_Email");

                    b.Property<string>("EFname")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("E_Fname");

                    b.Property<string>("EGender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("E_Gender");

                    b.Property<int?>("EId")
                        .HasColumnType("int")
                        .HasColumnName("E_ID");

                    b.Property<string>("ELname")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("E_Lname");

                    b.Property<string>("EMobileNo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("E_MobileNo");

                    b.Property<string>("EPass")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("E_Pass");

                    b.Property<int?>("ERoleId")
                        .HasColumnType("int")
                        .HasColumnName("E_RoleID");

                    b.Property<decimal?>("ESalary")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("E_Salary");

                    b.Property<string>("EStatus")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("E_Status");

                    b.Property<string>("ETelNo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("E_TelNo");

                    b.Property<string>("OperationPerform")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("operation_perform");

                    b.ToTable("EventOnEmployee", (string)null);
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Exam", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Exam_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamId"));

                    b.Property<int>("ExamClassId")
                        .HasColumnType("int")
                        .HasColumnName("Exam_ClassID");

                    b.Property<DateTime>("ExamStartDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Exam_Start_DateTime");

                    b.Property<int>("ExamSubjectId")
                        .HasColumnType("int")
                        .HasColumnName("Exam_SubjectID");

                    b.Property<int>("ExamTypeId")
                        .HasColumnType("int")
                        .HasColumnName("Exam_TypeID");

                    b.HasKey("ExamId");

                    b.HasIndex("ExamClassId");

                    b.HasIndex("ExamSubjectId");

                    b.HasIndex("ExamTypeId");

                    b.ToTable("Exam", (string)null);
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.ExamResult", b =>
                {
                    b.Property<int>("ExamResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ExamResult_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamResultId"));

                    b.Property<string>("ExamGrade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Exam_Grade");

                    b.Property<int>("ExamId")
                        .HasColumnType("int")
                        .HasColumnName("Exam_ID");

                    b.Property<decimal>("ExamObtainMarks")
                        .HasColumnType("decimal(10, 0)")
                        .HasColumnName("Exam_ObtainMarks");

                    b.Property<int>("ExamStdId")
                        .HasColumnType("int")
                        .HasColumnName("Exam_StdID");

                    b.Property<decimal>("ExamTotalMarks")
                        .HasColumnType("decimal(10, 0)")
                        .HasColumnName("Exam_TotalMarks");

                    b.HasKey("ExamResultId");

                    b.HasIndex("ExamId");

                    b.HasIndex("ExamStdId");

                    b.ToTable("Exam_Result", (string)null);
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.ExamType", b =>
                {
                    b.Property<int>("ExamTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Exam_TypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamTypeId"));

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Not Provided");

                    b.Property<string>("ExamName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Exam_Name");

                    b.HasKey("ExamTypeId");

                    b.HasIndex(new[] { "ExamName" }, "UQ_Exam_Type_Name")
                        .IsUnique();

                    b.ToTable("Exam_Type", (string)null);
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Fee", b =>
                {
                    b.Property<int>("FeesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Fees_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeesId"));

                    b.Property<decimal?>("FeesAdditionalCharges")
                        .HasColumnType("decimal(10, 0)")
                        .HasColumnName("Fees_AdditionalCharges");

                    b.Property<decimal>("FeesAmount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Fees_Amount");

                    b.Property<decimal?>("FeesDiscount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Fees_Discount");

                    b.Property<string>("FeesDiscountReason")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("Fees_DiscountReason");

                    b.Property<DateTime>("FeesDueDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Fees_DueDateTime");

                    b.Property<DateTime>("FeesIssueDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Fees_IssueDateTime");

                    b.Property<DateOnly?>("FeesPaidDate")
                        .HasColumnType("date")
                        .HasColumnName("Fees_PaidDate");

                    b.Property<decimal>("FeesPreviousCharges")
                        .HasColumnType("decimal(10, 0)")
                        .HasColumnName("Fees_PreviousCharges");

                    b.Property<string>("FeesStatus")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("FeesStdId")
                        .HasColumnType("int")
                        .HasColumnName("Fees_StdID");

                    b.HasKey("FeesId");

                    b.HasIndex("FeesStdId");

                    b.ToTable("Fees");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Guardian", b =>
                {
                    b.Property<int>("GrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Gr_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrId"));

                    b.Property<string>("GrAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Gr_Address");

                    b.Property<string>("GrCnic")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Gr_CNIC");

                    b.Property<string>("GrEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Gr_Email");

                    b.Property<string>("GrFname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Gr_Fname");

                    b.Property<string>("GrLname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Gr_Lname");

                    b.Property<string>("GrMobileNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Gr_MobileNo");

                    b.Property<string>("GrPass")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Gr_Pass");

                    b.Property<string>("GrRelationship")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Gr_Relationship");

                    b.Property<string>("GrTelNo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Gr_TelNo");

                    b.HasKey("GrId");

                    b.HasIndex(new[] { "GrCnic" }, "UQ_Guardian_CNIC")
                        .IsUnique();

                    b.HasIndex(new[] { "GrEmail" }, "UQ_Guardian_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "GrMobileNo" }, "UQ_Guardian_Mobile")
                        .IsUnique();

                    b.ToTable("Guardian", (string)null);
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Result", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Result_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<int>("ResultExamTypeId")
                        .HasColumnType("int")
                        .HasColumnName("Result_ExamTypeID");

                    b.Property<string>("ResultGrade")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("Result_Grade");

                    b.Property<decimal>("ResultObtainMarks")
                        .HasColumnType("decimal(10, 0)")
                        .HasColumnName("Result_ObtainMarks");

                    b.Property<decimal>("ResultPercentage")
                        .HasColumnType("decimal(10, 3)")
                        .HasColumnName("Result_Percentage");

                    b.Property<int>("ResultStdId")
                        .HasColumnType("int")
                        .HasColumnName("Result_StdID");

                    b.Property<decimal>("ResultTotalMarks")
                        .HasColumnType("decimal(10, 0)")
                        .HasColumnName("Result_TotalMarks");

                    b.HasKey("ResultId");

                    b.ToTable("Result", (string)null);
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Role_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Role_Name");

                    b.HasKey("RoleId");

                    b.HasIndex(new[] { "RoleName" }, "UQ_Role_Name")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Section", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Section_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectionId"));

                    b.Property<int>("SectionClassId")
                        .HasColumnType("int")
                        .HasColumnName("Section_ClassID");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("Section_Name");

                    b.Property<int>("SectionUnderObservation")
                        .HasColumnType("int")
                        .HasColumnName("Section_UnderObservation");

                    b.HasKey("SectionId");

                    b.HasIndex("SectionClassId");

                    b.HasIndex("SectionUnderObservation");

                    b.ToTable("Section", (string)null);
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Student", b =>
                {
                    b.Property<int>("StdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Std_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StdId"));

                    b.Property<int?>("StdClassId")
                        .HasColumnType("int")
                        .HasColumnName("Std_ClassID");

                    b.Property<DateOnly>("StdDoa")
                        .HasColumnType("date")
                        .HasColumnName("Std_DOA");

                    b.Property<DateOnly>("StdDob")
                        .HasColumnType("date")
                        .HasColumnName("Std_DOB");

                    b.Property<string>("StdEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Std_Email");

                    b.Property<string>("StdFname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Std_Fname");

                    b.Property<string>("StdGender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Std_Gender");

                    b.Property<int?>("StdGuardianId")
                        .HasColumnType("int")
                        .HasColumnName("Std_GuardianID");

                    b.Property<string>("StdLname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Std_Lname");

                    b.Property<string>("StdMobileNo")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Not Provided")
                        .HasColumnName("Std_MobileNo");

                    b.Property<string>("StdPass")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Std_Pass");

                    b.Property<int?>("StdSectionId")
                        .HasColumnType("int")
                        .HasColumnName("Std_SectionID");

                    b.Property<string>("StdStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Std_Status");

                    b.Property<string>("StdTelNo")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Not Provided")
                        .HasColumnName("Std_TelNo");

                    b.HasKey("StdId");

                    b.HasIndex("StdClassId");

                    b.HasIndex("StdGuardianId");

                    b.HasIndex("StdSectionId");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Subject_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<int>("SubjectClassId")
                        .HasColumnType("int")
                        .HasColumnName("Subject_ClassID");

                    b.Property<string>("SubjectDescription")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Not Provided")
                        .HasColumnName("Subject_Description");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Subject_Name");

                    b.HasKey("SubjectId");

                    b.HasIndex("SubjectClassId");

                    b.HasIndex(new[] { "SubjectName" }, "UQ_Subject_Name")
                        .IsUnique();

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.SubjectTeach", b =>
                {
                    b.Property<int>("IdSubjectTeaches")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idSubjectTeaches");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSubjectTeaches"));

                    b.Property<int>("SubjectTeachesBy")
                        .HasColumnType("int");

                    b.Property<int>("SubjectTeachesClassId")
                        .HasColumnType("int")
                        .HasColumnName("SubjectTeachesClassID");

                    b.Property<string>("SubjectTeachesDropStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasDefaultValue("Not Provided");

                    b.Property<DateOnly?>("SubjectTeachesEndDate")
                        .HasColumnType("date");

                    b.Property<string>("SubjectTeachesOutCome")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasDefaultValue("Not Provided");

                    b.Property<DateOnly>("SubjectTeachesStartDate")
                        .HasColumnType("date");

                    b.Property<int>("SubjectTeachesSubjectId")
                        .HasColumnType("int")
                        .HasColumnName("SubjectTeaches_SubjectID");

                    b.HasKey("IdSubjectTeaches");

                    b.HasIndex("SubjectTeachesBy");

                    b.HasIndex("SubjectTeachesClassId");

                    b.HasIndex("SubjectTeachesSubjectId");

                    b.ToTable("SubjectTeaches");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.TimeTable", b =>
                {
                    b.Property<int>("TtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TtId"));

                    b.Property<string>("TtDay")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("TT_Day");

                    b.Property<string>("TtDescription")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("TT_Description");

                    b.Property<TimeOnly>("TtEndTime")
                        .HasColumnType("time")
                        .HasColumnName("TT_EndTime");

                    b.Property<int>("TtSectionId")
                        .HasColumnType("int")
                        .HasColumnName("TT_SectionID");

                    b.Property<TimeOnly>("TtStartTime")
                        .HasColumnType("time")
                        .HasColumnName("TT_StartTime");

                    b.Property<int>("TtSubjectId")
                        .HasColumnType("int")
                        .HasColumnName("TT_SubjectID");

                    b.HasKey("TtId");

                    b.HasIndex("TtSectionId");

                    b.HasIndex("TtSubjectId");

                    b.ToTable("TimeTable", (string)null);
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Attendance", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Student", "AStd")
                        .WithMany()
                        .HasForeignKey("AStdId")
                        .IsRequired()
                        .HasConstraintName("FK_Attendance_Student");

                    b.Navigation("AStd");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Employee", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Role", "ERole")
                        .WithMany("Employees")
                        .HasForeignKey("ERoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Employee_Role");

                    b.Navigation("ERole");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Exam", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Classroom", "ExamClass")
                        .WithMany("Exams")
                        .HasForeignKey("ExamClassId")
                        .IsRequired()
                        .HasConstraintName("FK_Exam_Classroom");

                    b.HasOne("SchoolManagementSystem.Models.Subject", "ExamSubject")
                        .WithMany("Exams")
                        .HasForeignKey("ExamSubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Exam_Subjects");

                    b.HasOne("SchoolManagementSystem.Models.ExamType", "ExamType")
                        .WithMany("Exams")
                        .HasForeignKey("ExamTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Exam_Type");

                    b.Navigation("ExamClass");

                    b.Navigation("ExamSubject");

                    b.Navigation("ExamType");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.ExamResult", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Exam", "Exam")
                        .WithMany("ExamResults")
                        .HasForeignKey("ExamId")
                        .IsRequired()
                        .HasConstraintName("FK_ExamResult_Exam");

                    b.HasOne("SchoolManagementSystem.Models.Student", "ExamStd")
                        .WithMany("ExamResults")
                        .HasForeignKey("ExamStdId")
                        .IsRequired()
                        .HasConstraintName("FK_ExamResult_Student");

                    b.Navigation("Exam");

                    b.Navigation("ExamStd");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Fee", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Student", "FeesStd")
                        .WithMany("Fees")
                        .HasForeignKey("FeesStdId")
                        .IsRequired()
                        .HasConstraintName("FK_Fees_Student");

                    b.Navigation("FeesStd");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Section", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Classroom", "SectionClass")
                        .WithMany("Sections")
                        .HasForeignKey("SectionClassId")
                        .IsRequired()
                        .HasConstraintName("FK_Section_Classroom");

                    b.HasOne("SchoolManagementSystem.Models.Employee", "SectionUnderObservationNavigation")
                        .WithMany("Sections")
                        .HasForeignKey("SectionUnderObservation")
                        .IsRequired()
                        .HasConstraintName("FK_Section_Employee");

                    b.Navigation("SectionClass");

                    b.Navigation("SectionUnderObservationNavigation");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Student", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Classroom", "StdClass")
                        .WithMany("Students")
                        .HasForeignKey("StdClassId")
                        .HasConstraintName("FK_Student_Classroom");

                    b.HasOne("SchoolManagementSystem.Models.Guardian", "StdGuardian")
                        .WithMany("Students")
                        .HasForeignKey("StdGuardianId")
                        .HasConstraintName("FK_Student_Guardian");

                    b.HasOne("SchoolManagementSystem.Models.Section", "StdSection")
                        .WithMany("Students")
                        .HasForeignKey("StdSectionId")
                        .HasConstraintName("FK_Student_Section");

                    b.Navigation("StdClass");

                    b.Navigation("StdGuardian");

                    b.Navigation("StdSection");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Subject", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Classroom", "SubjectClass")
                        .WithMany("Subjects")
                        .HasForeignKey("SubjectClassId")
                        .IsRequired()
                        .HasConstraintName("FK_Subjects_Classroom");

                    b.Navigation("SubjectClass");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.SubjectTeach", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Employee", "SubjectTeachesByNavigation")
                        .WithMany("SubjectTeaches")
                        .HasForeignKey("SubjectTeachesBy")
                        .IsRequired()
                        .HasConstraintName("FK_SubjectTeaches_Employee");

                    b.HasOne("SchoolManagementSystem.Models.Classroom", "SubjectTeachesClass")
                        .WithMany("SubjectTeaches")
                        .HasForeignKey("SubjectTeachesClassId")
                        .IsRequired()
                        .HasConstraintName("FK_SubjectTeaches_Classroom");

                    b.HasOne("SchoolManagementSystem.Models.Subject", "SubjectTeachesSubject")
                        .WithMany("SubjectTeaches")
                        .HasForeignKey("SubjectTeachesSubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_SubjectTeaches_Subject");

                    b.Navigation("SubjectTeachesByNavigation");

                    b.Navigation("SubjectTeachesClass");

                    b.Navigation("SubjectTeachesSubject");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.TimeTable", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.Section", "TtSection")
                        .WithMany("TimeTables")
                        .HasForeignKey("TtSectionId")
                        .IsRequired()
                        .HasConstraintName("FK_TimeTable_Section");

                    b.HasOne("SchoolManagementSystem.Models.Subject", "TtSubject")
                        .WithMany("TimeTables")
                        .HasForeignKey("TtSubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_TimeTable_Subjects");

                    b.Navigation("TtSection");

                    b.Navigation("TtSubject");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Classroom", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("Sections");

                    b.Navigation("Students");

                    b.Navigation("SubjectTeaches");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Employee", b =>
                {
                    b.Navigation("Sections");

                    b.Navigation("SubjectTeaches");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Exam", b =>
                {
                    b.Navigation("ExamResults");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.ExamType", b =>
                {
                    b.Navigation("Exams");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Guardian", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Role", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Section", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("TimeTables");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Student", b =>
                {
                    b.Navigation("ExamResults");

                    b.Navigation("Fees");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.Subject", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("SubjectTeaches");

                    b.Navigation("TimeTables");
                });
#pragma warning restore 612, 618
        }
    }
}
